site_name: 'Documentation'
theme: 'material'
site_favicon: 'favicon.ico'
extra:
  logo: 'images/logo.png'
  author:
    github: 'Lerg'
    twitter: 'SergeyLerg'
  palette:
    primary: 'teal'
    accent: 'green'
markdown_extensions:
  - admonition
  - codehilite(css_class=code)
  - superscript
extra_css: ['/stylesheets/extra.css']
extra_javascript: ['/javascripts/extra.js']
