baseURL = "http://docs.spiralcodestudio.com/"
languageCode = "en-us"
title = "Documentation Spiral Code Studio"
theme = "docdock"
pygmentsStyle = "native"
disablePathToLower = true

[params]
ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]
