baseURL = "http://docs.spiralcodestudio.com/"
languageCode = "en-us"
title = "Documentation Spiral Code Studio"
theme = "docdock"
pygmentsStyle = "native"
disablePathToLower = true

[params]
editURL = "https://github.com/Lerg/docs/edit/master/docs/content/"
themeStyle = "flex"
ordersectionsby = "title"
disableHomeIcon = true
disableSearch = true
disableNavChevron = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
